// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20230312212306_migtationthree")]
    partial class migtationthree
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Admin.Admins", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCabinet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("IdCabinet");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("Server.Models.Analyse.Analyses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdOrdreMedical")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPharmacist")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MedicalAnalyseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("pharmacistsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdreMedical");

                    b.HasIndex("MedicalAnalyseId");

                    b.HasIndex("pharmacistsId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("Server.Models.CabinetMedicals.CabinetMedical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCabinet")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NameCabinet");

                    b.ToTable("cabinetMedicals");
                });

            modelBuilder.Entity("Server.Models.ChronicDiseases.ChronicDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameChronicDiseases")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("chronicDiseases");
                });

            modelBuilder.Entity("Server.Models.Doctor.Doctors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberRRPS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusDoctor")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Server.Models.FileChronicDisease.FileChronicDiseases", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdChronicDisease")
                        .HasColumnType("int");

                    b.Property<Guid>("IdFile")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("chronicDiseaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFile");

                    b.HasIndex("chronicDiseaseId");

                    b.ToTable("FileChronicDiseases");
                });

            modelBuilder.Entity("Server.Models.MedicalAnalysis.MedicalAnalyse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthenticationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameMedicalAnalyse")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("userAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NameMedicalAnalyse");

                    b.HasIndex("userAccountId");

                    b.ToTable("medicalAnalyses");
                });

            modelBuilder.Entity("Server.Models.MedicalOrder.MedicalOrdres", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileMedicalsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFileMedical")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSecritary")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileMedicalsId");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("IdSecritary");

                    b.ToTable("MedicalOrdres");
                });

            modelBuilder.Entity("Server.Models.MedicalPlannings.MedicalPlanning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppointmentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCabinet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("doctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdCabinet");

                    b.HasIndex("doctorId");

                    b.HasIndex("userId");

                    b.ToTable("medicalPlannings");
                });

            modelBuilder.Entity("Server.Models.Pharmacist.Pharmacists", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdressPharmacist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthenticationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharmacistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PharmacistName");

                    b.HasIndex("idUser");

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("Server.Models.PrescriptionLine.PrescriptionLines", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dosage")
                        .HasColumnType("int");

                    b.Property<Guid>("IdPharmacist")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPrescription")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MedicamentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusPrescriptionLine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPharmacist");

                    b.HasIndex("IdPrescription");

                    b.ToTable("PrescriptionLines");
                });

            modelBuilder.Entity("Server.Models.Prescriptions.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMedicalOrdre")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdMedicalOrdre");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("Server.Models.RadioMedical.Radio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdOrdreMedical")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRadiology")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdreMedical");

                    b.HasIndex("IdRadiology");

                    b.ToTable("Radio");
                });

            modelBuilder.Entity("Server.Models.Radiologys.Radiology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Materiel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDoctor");

                    b.ToTable("radiologies");
                });

            modelBuilder.Entity("Server.Models.ResultAnalyses.ResultAnalyse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<Guid>("IdAnalyse")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("analysesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("analysesId");

                    b.ToTable("resultAnalyses");
                });

            modelBuilder.Entity("Server.Models.ResultsRadio.ResultRadio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<Guid>("IdRadio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdRadio");

                    b.ToTable("RadioResult");
                });

            modelBuilder.Entity("Server.Models.Specialites.Specialite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameSpecialite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("specialites");
                });

            modelBuilder.Entity("Server.Models.SpecialtieDoctor.SpecialtiesDoctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdSpecialites")
                        .HasColumnType("int");

                    b.Property<int>("Specialite")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("Specialite");

                    b.ToTable("specialtiesDoctors");
                });

            modelBuilder.Entity("Server.Models.UserAccount.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Server.Models.UserAccount.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateExpireRefreshToken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexe")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Server.Models.UserRoles.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("RoleId");

                    b.ToTable("userRoles");
                });

            modelBuilder.Entity("Server.Models.WorkDoctor.WorkDoctors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCabinet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NbPatientAvailble")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadyTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusWork")
                        .HasColumnType("int");

                    b.Property<Guid>("cabinetMedicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("statusReservation")
                        .HasColumnType("int");

                    b.Property<int>("statusServcie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("cabinetMedicalId");

                    b.ToTable("WorkDoctors");
                });

            modelBuilder.Entity("Server.Models.fileMedical.fileMedicals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MedicalIdentification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexe")
                        .HasColumnType("int");

                    b.Property<Guid>("doctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("doctorId");

                    b.HasIndex("userId");

                    b.HasIndex("firstname", "Lastname");

                    b.ToTable("fileMedicals");
                });

            modelBuilder.Entity("Server.Models.secretary.Secretarys", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCabinetMedical")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("cabinetMedicalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("cabinetMedicalId");

                    b.ToTable("Secretarys");
                });

            modelBuilder.Entity("Server.Models.Admin.Admins", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "Doctor")
                        .WithMany("Admin")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.CabinetMedicals.CabinetMedical", "CabinetMedical")
                        .WithMany("Admins")
                        .HasForeignKey("IdCabinet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CabinetMedical");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Server.Models.Analyse.Analyses", b =>
                {
                    b.HasOne("Server.Models.MedicalOrder.MedicalOrdres", "MedicalOrdres")
                        .WithMany("Analyses")
                        .HasForeignKey("IdOrdreMedical")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.MedicalAnalysis.MedicalAnalyse", null)
                        .WithMany("Analyses")
                        .HasForeignKey("MedicalAnalyseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.Pharmacist.Pharmacists", "pharmacists")
                        .WithMany()
                        .HasForeignKey("pharmacistsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalOrdres");

                    b.Navigation("pharmacists");
                });

            modelBuilder.Entity("Server.Models.Doctor.Doctors", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "UserAccount")
                        .WithMany("Doctor")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Server.Models.FileChronicDisease.FileChronicDiseases", b =>
                {
                    b.HasOne("Server.Models.fileMedical.fileMedicals", "fileMedicals")
                        .WithMany("FileChronicDiseases")
                        .HasForeignKey("IdFile")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.ChronicDiseases.ChronicDisease", "chronicDisease")
                        .WithMany()
                        .HasForeignKey("chronicDiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("chronicDisease");

                    b.Navigation("fileMedicals");
                });

            modelBuilder.Entity("Server.Models.MedicalAnalysis.MedicalAnalyse", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "userAccount")
                        .WithMany("MedicalAnalyse")
                        .HasForeignKey("userAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("userAccount");
                });

            modelBuilder.Entity("Server.Models.MedicalOrder.MedicalOrdres", b =>
                {
                    b.HasOne("Server.Models.fileMedical.fileMedicals", "FileMedicals")
                        .WithMany("MedicalOrders")
                        .HasForeignKey("FileMedicalsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Doctor.Doctors", "Doctors")
                        .WithMany("MedicalOrder")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.secretary.Secretarys", "Secretarys")
                        .WithMany("MedicalOrdres")
                        .HasForeignKey("IdSecritary")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctors");

                    b.Navigation("FileMedicals");

                    b.Navigation("Secretarys");
                });

            modelBuilder.Entity("Server.Models.MedicalPlannings.MedicalPlanning", b =>
                {
                    b.HasOne("Server.Models.CabinetMedicals.CabinetMedical", "CabinetMedical")
                        .WithMany("MedicalPlanning")
                        .HasForeignKey("IdCabinet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Doctor.Doctors", "doctor")
                        .WithMany("MedicalPlanning")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.UserAccount.User", "user")
                        .WithMany("MedicalPlanning")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CabinetMedical");

                    b.Navigation("doctor");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Server.Models.Pharmacist.Pharmacists", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "User")
                        .WithMany("pharmacists")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.PrescriptionLine.PrescriptionLines", b =>
                {
                    b.HasOne("Server.Models.Pharmacist.Pharmacists", "Pharmacists")
                        .WithMany("PrescriptionLines")
                        .HasForeignKey("IdPharmacist")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Prescriptions.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("IdPrescription")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pharmacists");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Server.Models.Prescriptions.Prescription", b =>
                {
                    b.HasOne("Server.Models.MedicalOrder.MedicalOrdres", "MedicalOrdres")
                        .WithMany("prescriptions")
                        .HasForeignKey("IdMedicalOrdre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalOrdres");
                });

            modelBuilder.Entity("Server.Models.RadioMedical.Radio", b =>
                {
                    b.HasOne("Server.Models.MedicalOrder.MedicalOrdres", "MedicalOrdres")
                        .WithMany("Radios")
                        .HasForeignKey("IdOrdreMedical")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Radiologys.Radiology", "Radiology")
                        .WithMany("Radios")
                        .HasForeignKey("IdRadiology")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalOrdres");

                    b.Navigation("Radiology");
                });

            modelBuilder.Entity("Server.Models.Radiologys.Radiology", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "Doctors")
                        .WithMany("Radiology")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Server.Models.ResultAnalyses.ResultAnalyse", b =>
                {
                    b.HasOne("Server.Models.Analyse.Analyses", "analyses")
                        .WithMany("ResultAnalyse")
                        .HasForeignKey("analysesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("analyses");
                });

            modelBuilder.Entity("Server.Models.ResultsRadio.ResultRadio", b =>
                {
                    b.HasOne("Server.Models.RadioMedical.Radio", "Radio")
                        .WithMany("resultRadios")
                        .HasForeignKey("IdRadio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("Server.Models.SpecialtieDoctor.SpecialtiesDoctor", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "Doctors")
                        .WithMany("SpecialtiesDoctor")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Specialites.Specialite", "specialites")
                        .WithMany("specialtiesDoctors")
                        .HasForeignKey("Specialite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctors");

                    b.Navigation("specialites");
                });

            modelBuilder.Entity("Server.Models.UserRoles.UserRole", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "User")
                        .WithMany("usersRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.UserAccount.Role", "Role")
                        .WithMany("usersRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.WorkDoctor.WorkDoctors", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "Doctor")
                        .WithMany("WorkDoctor")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.CabinetMedicals.CabinetMedical", "cabinetMedical")
                        .WithMany("WorkDoctors")
                        .HasForeignKey("cabinetMedicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("cabinetMedical");
                });

            modelBuilder.Entity("Server.Models.fileMedical.fileMedicals", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "doctor")
                        .WithMany("fileMedical")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.UserAccount.User", "user")
                        .WithMany("fileMedical")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Server.Models.secretary.Secretarys", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "User")
                        .WithMany("Secretarys")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.CabinetMedicals.CabinetMedical", "cabinetMedical")
                        .WithMany("Secretarys")
                        .HasForeignKey("cabinetMedicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("cabinetMedical");
                });

            modelBuilder.Entity("Server.Models.Analyse.Analyses", b =>
                {
                    b.Navigation("ResultAnalyse");
                });

            modelBuilder.Entity("Server.Models.CabinetMedicals.CabinetMedical", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("MedicalPlanning");

                    b.Navigation("Secretarys");

                    b.Navigation("WorkDoctors");
                });

            modelBuilder.Entity("Server.Models.Doctor.Doctors", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("MedicalOrder");

                    b.Navigation("MedicalPlanning");

                    b.Navigation("Radiology");

                    b.Navigation("SpecialtiesDoctor");

                    b.Navigation("WorkDoctor");

                    b.Navigation("fileMedical");
                });

            modelBuilder.Entity("Server.Models.MedicalAnalysis.MedicalAnalyse", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("Server.Models.MedicalOrder.MedicalOrdres", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Radios");

                    b.Navigation("prescriptions");
                });

            modelBuilder.Entity("Server.Models.Pharmacist.Pharmacists", b =>
                {
                    b.Navigation("PrescriptionLines");
                });

            modelBuilder.Entity("Server.Models.RadioMedical.Radio", b =>
                {
                    b.Navigation("resultRadios");
                });

            modelBuilder.Entity("Server.Models.Radiologys.Radiology", b =>
                {
                    b.Navigation("Radios");
                });

            modelBuilder.Entity("Server.Models.Specialites.Specialite", b =>
                {
                    b.Navigation("specialtiesDoctors");
                });

            modelBuilder.Entity("Server.Models.UserAccount.Role", b =>
                {
                    b.Navigation("usersRoles");
                });

            modelBuilder.Entity("Server.Models.UserAccount.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("MedicalAnalyse");

                    b.Navigation("MedicalPlanning");

                    b.Navigation("Secretarys");

                    b.Navigation("fileMedical");

                    b.Navigation("pharmacists");

                    b.Navigation("usersRoles");
                });

            modelBuilder.Entity("Server.Models.fileMedical.fileMedicals", b =>
                {
                    b.Navigation("FileChronicDiseases");

                    b.Navigation("MedicalOrders");
                });

            modelBuilder.Entity("Server.Models.secretary.Secretarys", b =>
                {
                    b.Navigation("MedicalOrdres");
                });
#pragma warning restore 612, 618
        }
    }
}
