// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20230313214116_migrationeight")]
    partial class migrationeight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Admin.Admins", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCabinet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("IdCabinet");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("Server.Models.Analyse.Analyses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdOrdreMedical")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPharmacist")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MedicalAnalyseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("pharmacistsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdreMedical");

                    b.HasIndex("MedicalAnalyseId");

                    b.HasIndex("pharmacistsId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("Server.Models.CabinetMedicals.CabinetMedical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCabinet")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NameCabinet");

                    b.ToTable("cabinetMedicals");
                });

            modelBuilder.Entity("Server.Models.ChronicDiseases.ChronicDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameChronicDiseases")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("chronicDiseases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameChronicDiseases = "DIABÈTE"
                        },
                        new
                        {
                            Id = 2,
                            NameChronicDiseases = "HYPERTENSION-ARTÉRIELLE"
                        },
                        new
                        {
                            Id = 3,
                            NameChronicDiseases = "MALADIES-RESPIRATOIRES"
                        },
                        new
                        {
                            Id = 4,
                            NameChronicDiseases = "MALADIES RÉNALES"
                        },
                        new
                        {
                            Id = 5,
                            NameChronicDiseases = "MALADIES ARTICULAIRES"
                        },
                        new
                        {
                            Id = 6,
                            NameChronicDiseases = "MALADIES DU FOIE"
                        },
                        new
                        {
                            Id = 7,
                            NameChronicDiseases = "MALADIES NEUROLOGIQUES"
                        },
                        new
                        {
                            Id = 8,
                            NameChronicDiseases = "CANCER"
                        },
                        new
                        {
                            Id = 9,
                            NameChronicDiseases = "MALADIES-CARDIOVASCULAIRES"
                        });
                });

            modelBuilder.Entity("Server.Models.Doctor.Doctors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberRRPS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusDoctor")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Server.Models.FileChronicDisease.FileChronicDiseases", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdChronicDisease")
                        .HasColumnType("int");

                    b.Property<Guid>("IdFile")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("chronicDiseaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFile");

                    b.HasIndex("chronicDiseaseId");

                    b.ToTable("FileChronicDiseases");
                });

            modelBuilder.Entity("Server.Models.MedicalAnalysis.MedicalAnalyse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthenticationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameMedicalAnalyse")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("userAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NameMedicalAnalyse");

                    b.HasIndex("userAccountId");

                    b.ToTable("medicalAnalyses");
                });

            modelBuilder.Entity("Server.Models.MedicalOrder.MedicalOrdres", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileMedicalsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFileMedical")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSecritary")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileMedicalsId");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("IdSecritary");

                    b.ToTable("MedicalOrdres");
                });

            modelBuilder.Entity("Server.Models.MedicalPlannings.MedicalPlanning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppointmentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCabinet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("doctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdCabinet");

                    b.HasIndex("doctorId");

                    b.HasIndex("userId");

                    b.ToTable("medicalPlannings");
                });

            modelBuilder.Entity("Server.Models.Pharmacist.Pharmacists", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdressPharmacist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthenticationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharmacistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PharmacistName");

                    b.HasIndex("idUser");

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("Server.Models.PrescriptionLine.PrescriptionLines", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dosage")
                        .HasColumnType("int");

                    b.Property<Guid>("IdPharmacist")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPrescription")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MedicamentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusPrescriptionLine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPharmacist");

                    b.HasIndex("IdPrescription");

                    b.ToTable("PrescriptionLines");
                });

            modelBuilder.Entity("Server.Models.Prescriptions.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMedicalOrdre")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdMedicalOrdre");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("Server.Models.RadioMedical.Radio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdOrdreMedical")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRadiology")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdreMedical");

                    b.HasIndex("IdRadiology");

                    b.ToTable("Radio");
                });

            modelBuilder.Entity("Server.Models.Radiologys.Radiology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Materiel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDoctor");

                    b.ToTable("radiologies");
                });

            modelBuilder.Entity("Server.Models.ResultAnalyses.ResultAnalyse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<Guid>("IdAnalyse")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("analysesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("analysesId");

                    b.ToTable("resultAnalyses");
                });

            modelBuilder.Entity("Server.Models.ResultsRadio.ResultRadio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<Guid>("IdRadio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdRadio");

                    b.ToTable("RadioResult");
                });

            modelBuilder.Entity("Server.Models.Specialites.Specialite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameSpecialite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("specialites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameSpecialite = "ANESTHÉSIOLOGIE"
                        },
                        new
                        {
                            Id = 2,
                            NameSpecialite = "CARDIOLOGIE"
                        },
                        new
                        {
                            Id = 3,
                            NameSpecialite = "CHIRURGIE"
                        },
                        new
                        {
                            Id = 4,
                            NameSpecialite = "DERMATOLOGIE"
                        },
                        new
                        {
                            Id = 5,
                            NameSpecialite = "ENDOCRINOLOGIE"
                        },
                        new
                        {
                            Id = 6,
                            NameSpecialite = "GASTRO ENTÉROLOGIE"
                        },
                        new
                        {
                            Id = 7,
                            NameSpecialite = "GYNÉCOLOGIE"
                        },
                        new
                        {
                            Id = 8,
                            NameSpecialite = "HÉMATOLOGIE"
                        },
                        new
                        {
                            Id = 9,
                            NameSpecialite = "INFECTIOLOGIE"
                        },
                        new
                        {
                            Id = 10,
                            NameSpecialite = "MÉDECINE DU TRAVAIL"
                        },
                        new
                        {
                            Id = 11,
                            NameSpecialite = "MÉDECINE INTERNE"
                        },
                        new
                        {
                            Id = 12,
                            NameSpecialite = "NÉPHROLOGIE"
                        },
                        new
                        {
                            Id = 13,
                            NameSpecialite = "NEUROLOGIE"
                        },
                        new
                        {
                            Id = 14,
                            NameSpecialite = "OBSTÉTRIQUE"
                        },
                        new
                        {
                            Id = 15,
                            NameSpecialite = "ONCOLOGIE"
                        },
                        new
                        {
                            Id = 16,
                            NameSpecialite = "OPHTALMOLOGIE"
                        },
                        new
                        {
                            Id = 17,
                            NameSpecialite = "ORTHOPÉDIE"
                        },
                        new
                        {
                            Id = 18,
                            NameSpecialite = "OTO-RHINO-LARYNGOLOGIE"
                        },
                        new
                        {
                            Id = 19,
                            NameSpecialite = "PÉDIATRIE"
                        },
                        new
                        {
                            Id = 20,
                            NameSpecialite = "PNEUMOLOGIE"
                        },
                        new
                        {
                            Id = 21,
                            NameSpecialite = "PSYCHIATRIE"
                        },
                        new
                        {
                            Id = 22,
                            NameSpecialite = "RADIOLOGIE"
                        },
                        new
                        {
                            Id = 23,
                            NameSpecialite = "RHUMATOLOGIE"
                        },
                        new
                        {
                            Id = 24,
                            NameSpecialite = "URGENTISTE"
                        });
                });

            modelBuilder.Entity("Server.Models.SpecialtieDoctor.SpecialtiesDoctor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdSpecialites")
                        .HasColumnType("int");

                    b.Property<int>("Specialite")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("Specialite");

                    b.ToTable("specialtiesDoctors");
                });

            modelBuilder.Entity("Server.Models.UserAccount.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c874c8da-1e00-4b95-b40c-5c875f763152"),
                            ConcurrencyStamp = "2ef8eb6f-9a72-4e26-a049-2288846f3320",
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d3aeb6de-1cd5-44cc-8c01-3cd5007648e4"),
                            ConcurrencyStamp = "d07b50d5-99c1-45c9-a01d-9cfd1ce56447",
                            Name = "PATIENT"
                        },
                        new
                        {
                            Id = new Guid("7e6377fd-f844-4ca5-9d62-92a4046123cc"),
                            ConcurrencyStamp = "44033e2f-685f-4304-84b8-f8e0eceafc5d",
                            Name = "SECRITAIRE"
                        },
                        new
                        {
                            Id = new Guid("ec13cdfe-8476-4a74-9822-78a5a46f1cf9"),
                            ConcurrencyStamp = "08dfe806-5827-441e-8faa-54461c323171",
                            Name = "MEDECIN"
                        },
                        new
                        {
                            Id = new Guid("8115b9d2-c135-4f56-ac93-8885dc90b87f"),
                            ConcurrencyStamp = "7796ae76-d422-4abf-ac8a-8a1365be9950",
                            Name = "RADIOLOGUE"
                        },
                        new
                        {
                            Id = new Guid("d05559ca-ac12-4cf2-b302-e6f6770f54f4"),
                            ConcurrencyStamp = "15be138a-d58b-47f9-92b6-f659a3849565",
                            Name = "PHARMACIEN"
                        },
                        new
                        {
                            Id = new Guid("71ea89ea-939b-4bf5-8e66-1d344264a577"),
                            ConcurrencyStamp = "87ff8b7f-b672-4d6e-8eae-f3437fdd4329",
                            Name = "ANALYSE"
                        });
                });

            modelBuilder.Entity("Server.Models.UserAccount.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreateAccount")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExpireRefreshToken")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexe")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Server.Models.UserRoles.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("RoleId");

                    b.ToTable("userRoles");
                });

            modelBuilder.Entity("Server.Models.WorkDoctor.WorkDoctors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCabinet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NbPatientAvailble")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadyTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusWork")
                        .HasColumnType("int");

                    b.Property<Guid>("cabinetMedicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("statusReservation")
                        .HasColumnType("int");

                    b.Property<int>("statusServcie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("cabinetMedicalId");

                    b.ToTable("WorkDoctors");
                });

            modelBuilder.Entity("Server.Models.fileMedical.fileMedicals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDoctor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MedicalIdentification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexe")
                        .HasColumnType("int");

                    b.Property<Guid>("doctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("doctorId");

                    b.HasIndex("userId");

                    b.HasIndex("firstname", "Lastname");

                    b.ToTable("fileMedicals");
                });

            modelBuilder.Entity("Server.Models.secretary.Secretarys", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCabinetMedical")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("cabinetMedicalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("cabinetMedicalId");

                    b.ToTable("Secretarys");
                });

            modelBuilder.Entity("Server.Models.Admin.Admins", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "Doctor")
                        .WithMany("Admin")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.CabinetMedicals.CabinetMedical", "CabinetMedical")
                        .WithMany("Admins")
                        .HasForeignKey("IdCabinet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CabinetMedical");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Server.Models.Analyse.Analyses", b =>
                {
                    b.HasOne("Server.Models.MedicalOrder.MedicalOrdres", "MedicalOrdres")
                        .WithMany("Analyses")
                        .HasForeignKey("IdOrdreMedical")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.MedicalAnalysis.MedicalAnalyse", null)
                        .WithMany("Analyses")
                        .HasForeignKey("MedicalAnalyseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.Pharmacist.Pharmacists", "pharmacists")
                        .WithMany()
                        .HasForeignKey("pharmacistsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalOrdres");

                    b.Navigation("pharmacists");
                });

            modelBuilder.Entity("Server.Models.Doctor.Doctors", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "UserAccount")
                        .WithMany("Doctor")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Server.Models.FileChronicDisease.FileChronicDiseases", b =>
                {
                    b.HasOne("Server.Models.fileMedical.fileMedicals", "fileMedicals")
                        .WithMany("FileChronicDiseases")
                        .HasForeignKey("IdFile")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.ChronicDiseases.ChronicDisease", "chronicDisease")
                        .WithMany()
                        .HasForeignKey("chronicDiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("chronicDisease");

                    b.Navigation("fileMedicals");
                });

            modelBuilder.Entity("Server.Models.MedicalAnalysis.MedicalAnalyse", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "userAccount")
                        .WithMany("MedicalAnalyse")
                        .HasForeignKey("userAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("userAccount");
                });

            modelBuilder.Entity("Server.Models.MedicalOrder.MedicalOrdres", b =>
                {
                    b.HasOne("Server.Models.fileMedical.fileMedicals", "FileMedicals")
                        .WithMany("MedicalOrders")
                        .HasForeignKey("FileMedicalsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Doctor.Doctors", "Doctors")
                        .WithMany("MedicalOrder")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.secretary.Secretarys", "Secretarys")
                        .WithMany("MedicalOrdres")
                        .HasForeignKey("IdSecritary")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctors");

                    b.Navigation("FileMedicals");

                    b.Navigation("Secretarys");
                });

            modelBuilder.Entity("Server.Models.MedicalPlannings.MedicalPlanning", b =>
                {
                    b.HasOne("Server.Models.CabinetMedicals.CabinetMedical", "CabinetMedical")
                        .WithMany("MedicalPlanning")
                        .HasForeignKey("IdCabinet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Doctor.Doctors", "doctor")
                        .WithMany("MedicalPlanning")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.UserAccount.User", "user")
                        .WithMany("MedicalPlanning")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CabinetMedical");

                    b.Navigation("doctor");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Server.Models.Pharmacist.Pharmacists", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "User")
                        .WithMany("pharmacists")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.PrescriptionLine.PrescriptionLines", b =>
                {
                    b.HasOne("Server.Models.Pharmacist.Pharmacists", "Pharmacists")
                        .WithMany("PrescriptionLines")
                        .HasForeignKey("IdPharmacist")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Prescriptions.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("IdPrescription")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pharmacists");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Server.Models.Prescriptions.Prescription", b =>
                {
                    b.HasOne("Server.Models.MedicalOrder.MedicalOrdres", "MedicalOrdres")
                        .WithMany("prescriptions")
                        .HasForeignKey("IdMedicalOrdre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalOrdres");
                });

            modelBuilder.Entity("Server.Models.RadioMedical.Radio", b =>
                {
                    b.HasOne("Server.Models.MedicalOrder.MedicalOrdres", "MedicalOrdres")
                        .WithMany("Radios")
                        .HasForeignKey("IdOrdreMedical")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Radiologys.Radiology", "Radiology")
                        .WithMany("Radios")
                        .HasForeignKey("IdRadiology")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalOrdres");

                    b.Navigation("Radiology");
                });

            modelBuilder.Entity("Server.Models.Radiologys.Radiology", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "Doctors")
                        .WithMany("Radiology")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Server.Models.ResultAnalyses.ResultAnalyse", b =>
                {
                    b.HasOne("Server.Models.Analyse.Analyses", "analyses")
                        .WithMany("ResultAnalyse")
                        .HasForeignKey("analysesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("analyses");
                });

            modelBuilder.Entity("Server.Models.ResultsRadio.ResultRadio", b =>
                {
                    b.HasOne("Server.Models.RadioMedical.Radio", "Radio")
                        .WithMany("resultRadios")
                        .HasForeignKey("IdRadio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("Server.Models.SpecialtieDoctor.SpecialtiesDoctor", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "Doctors")
                        .WithMany("SpecialtiesDoctor")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Specialites.Specialite", "specialites")
                        .WithMany("specialtiesDoctors")
                        .HasForeignKey("Specialite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctors");

                    b.Navigation("specialites");
                });

            modelBuilder.Entity("Server.Models.UserRoles.UserRole", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "User")
                        .WithMany("usersRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.UserAccount.Role", "Role")
                        .WithMany("usersRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.WorkDoctor.WorkDoctors", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "Doctor")
                        .WithMany("WorkDoctor")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.CabinetMedicals.CabinetMedical", "cabinetMedical")
                        .WithMany("WorkDoctors")
                        .HasForeignKey("cabinetMedicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("cabinetMedical");
                });

            modelBuilder.Entity("Server.Models.fileMedical.fileMedicals", b =>
                {
                    b.HasOne("Server.Models.Doctor.Doctors", "doctor")
                        .WithMany("fileMedical")
                        .HasForeignKey("doctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.UserAccount.User", "user")
                        .WithMany("fileMedical")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Server.Models.secretary.Secretarys", b =>
                {
                    b.HasOne("Server.Models.UserAccount.User", "User")
                        .WithMany("Secretarys")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.CabinetMedicals.CabinetMedical", "cabinetMedical")
                        .WithMany("Secretarys")
                        .HasForeignKey("cabinetMedicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("cabinetMedical");
                });

            modelBuilder.Entity("Server.Models.Analyse.Analyses", b =>
                {
                    b.Navigation("ResultAnalyse");
                });

            modelBuilder.Entity("Server.Models.CabinetMedicals.CabinetMedical", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("MedicalPlanning");

                    b.Navigation("Secretarys");

                    b.Navigation("WorkDoctors");
                });

            modelBuilder.Entity("Server.Models.Doctor.Doctors", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("MedicalOrder");

                    b.Navigation("MedicalPlanning");

                    b.Navigation("Radiology");

                    b.Navigation("SpecialtiesDoctor");

                    b.Navigation("WorkDoctor");

                    b.Navigation("fileMedical");
                });

            modelBuilder.Entity("Server.Models.MedicalAnalysis.MedicalAnalyse", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("Server.Models.MedicalOrder.MedicalOrdres", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Radios");

                    b.Navigation("prescriptions");
                });

            modelBuilder.Entity("Server.Models.Pharmacist.Pharmacists", b =>
                {
                    b.Navigation("PrescriptionLines");
                });

            modelBuilder.Entity("Server.Models.RadioMedical.Radio", b =>
                {
                    b.Navigation("resultRadios");
                });

            modelBuilder.Entity("Server.Models.Radiologys.Radiology", b =>
                {
                    b.Navigation("Radios");
                });

            modelBuilder.Entity("Server.Models.Specialites.Specialite", b =>
                {
                    b.Navigation("specialtiesDoctors");
                });

            modelBuilder.Entity("Server.Models.UserAccount.Role", b =>
                {
                    b.Navigation("usersRoles");
                });

            modelBuilder.Entity("Server.Models.UserAccount.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("MedicalAnalyse");

                    b.Navigation("MedicalPlanning");

                    b.Navigation("Secretarys");

                    b.Navigation("fileMedical");

                    b.Navigation("pharmacists");

                    b.Navigation("usersRoles");
                });

            modelBuilder.Entity("Server.Models.fileMedical.fileMedicals", b =>
                {
                    b.Navigation("FileChronicDiseases");

                    b.Navigation("MedicalOrders");
                });

            modelBuilder.Entity("Server.Models.secretary.Secretarys", b =>
                {
                    b.Navigation("MedicalOrdres");
                });
#pragma warning restore 612, 618
        }
    }
}
